spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    password: 1122
    username: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      time-to-live: 600000
    cache-names: test-cache
mybatis:
  mapper-locations: classpath*:/mapper/blog/*.xml
  type-aliases-package: me.perol.blog.entity

